# Generated by Django 5.0.4 on 2024-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created_question',
            field=models.DateField(blank=True, null=True),
        ),
    ]
