# Generated by Django 5.0.4 on 2024-04-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_date_created_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
