# Generated by Django 5.0.4 on 2024-04-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_profile_created_at_remove_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
