# Generated by Django 5.0.4 on 2024-04-12 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_questions_answer_question_alter_answer_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_to',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='question',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(default='path/to/default/image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='Text', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating_likes', models.BigIntegerField(default=0)),
                ('rating_dislikes', models.BigIntegerField(default=0)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteToAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_vote_to_a', to='app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='VoteToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_vote_to_q', to='app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='VoteToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_vote', to='app.myuser')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_who_is_vote', to='app.myuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
