# Generated by Django 5.0.4 on 2024-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_tag_questions_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_path',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='questions/'),
        ),
    ]
